# Generated by Django 2.2.25 on 2022-03-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_delete_pipelineregistry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyarchive',
            name='archive_start',
            field=models.DateTimeField(db_index=True),
        ),
    ]
