# Generated by Django 2.2.25 on 2022-03-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0070_delete_pipelineregistry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadtracking',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='uploadtracking',
            name='last_updated',
        ),
    ]
