# Generated by Django 3.2.12 on 2022-04-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0073_auto_20220330_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestparam',
            name='default',
            field=models.BooleanField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foresttask',
            name='forest_output_exists',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
