# Generated by Django 3.2.12 on 2022-04-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0074_auto_20220407_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOSEDecryptionKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('s3_file_path', models.CharField(db_index=True, max_length=256, unique=True)),
                ('base64_encryption_key', models.CharField(max_length=256)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
