# Generated by Django 3.2.12 on 2022-04-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    dependencies = [
        ('database', '0075_iosedecryptionkey'),
    ]
    
    operations = [
        migrations.RenameModel('IOSEDecryptionKey', 'IOSDecryptionKey'),
        migrations.AlterField(
            model_name='iosdecryptionkey',
            name='base64_encryption_key',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='iosdecryptionkey',
            name='s3_file_path',
            field=models.CharField(db_index=True, max_length=80, unique=True),
        ),
        migrations.RenameField(
            model_name='iosdecryptionkey',
            old_name='s3_file_path',
            new_name='file_name',
        ),
    ]
