# Generated by Django 3.2.13 on 2022-05-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0077_delete_fileprocesslock'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(db_index=True, max_length=256)),
                ('note', models.TextField()),
                ('stacktrace', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
