# Generated by Django 3.2.13 on 2022-05-12 19:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0079_delete_decryptionkeyerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantfcmhistory',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ParticipantMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=3900)),
                ('schedule_type', models.TextField(choices=[('asap', 'as soon as possible'), ('absolute', 'at a specific date/time')])),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('scheduled_send_datetime', models.DateTimeField(blank=True, null=True)),
                ('datetime_sent', models.DateTimeField(blank=True, null=True)),
                ('status', models.TextField(choices=[('cancelled', 'Cancelled'), ('error', 'Error'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], default='scheduled')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_messages', to='database.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
