# Generated by Django 3.2.13 on 2022-06-28 19:53
import json

from django.db import migrations, models
import django.db.models.deletion


SYCAMORE_DEFAULTS = {
    "submits_timeframe": "daily",
    "tz_str": "America/New_York",
}


def backfill_sycamore_param(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ForestParam = apps.get_model("database", "ForestParam")
    objs = ForestParam.objects.using(db_alias).all()
    for obj in objs:
        obj.sycamore_json_string=json.dumps(SYCAMORE_DEFAULTS)
    ForestParam.objects.using(db_alias).bulk_update(objs, ['sycamore_json_string'])


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0079_delete_decryptionkeyerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='forestparam',
            name='sycamore_json_string',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sycamore_summary_statistics', to='database.foresttask'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_total_completed_surveys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_total_opened_surveys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_total_surveys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_average_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_submit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foresttask',
            name='forest_tree',
            field=models.TextField(choices=[('jasmine', 'Jasmine'), ('willow', 'Willow'), ('sycamore', 'Sycamore')]),
        ),
        migrations.RunPython(backfill_sycamore_param, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='forestparam',
            name='sycamore_json_string',
            field=models.TextField(),
        ),
    ]
