# Generated by Django 3.2.15 on 2022-08-11 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0080_summarystatisticdaily_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('tree_name', models.TextField(choices=[('jasmine', 'Jasmine'), ('willow', 'Willow'), ('sycamore', 'Sycamore')])),
                ('json_parameters', models.TextField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='study',
            name='forest_param',
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_average_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_average_time_to_submit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sycamore_summary_statistics', to='database.foresttask'),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_total_completed_surveys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_total_opened_surveys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='summarystatisticdaily',
            name='sycamore_total_surveys',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foresttask',
            name='forest_tree',
            field=models.TextField(choices=[('jasmine', 'Jasmine'), ('willow', 'Willow'), ('sycamore', 'Sycamore')]),
        ),
        migrations.AlterField(
            model_name='foresttask',
            name='forest_param',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='database.forestparameters'),
        ),
        migrations.DeleteModel(
            name='ForestParam',
        ),
    ]
