# Generated by Django 3.2.13 on 2022-06-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0080_auto_20220628_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestparam',
            name='sycamore_json_string',
            field=models.TextField(),
        ),
    ]
