# Generated by Django 3.2.15 on 2022-08-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0081_auto_20220811_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foresttask',
            name='forest_param',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='database.forestparameters'),
        ),
    ]
