# Generated by Django 3.2.15 on 2022-09-20 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0083_auto_20220909_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedevent',
            name='response_time',
        ),
        migrations.AddField(
            model_name='archivedevent',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_push_notification_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_push_notification_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_survey_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='checkin_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='most_recent_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='database.archivedevent'),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='archivedevent',
            name='schedule_type',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='archivedevent',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
