# Generated by Django 3.2.15 on 2022-10-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0084_auto_20220920_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='easy_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='easy_enrollment',
            field=models.BooleanField(default=False),
        ),
    ]
