# Generated by Django 3.2.15 on 2022-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0086_alter_scheduledevent_most_recent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='ambient_audio_bitrate',
            field=models.PositiveIntegerField(default=24000),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='ambient_audio_off_duration_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='ambient_audio_on_duration_seconds',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='ambient_audio_sampling_rate',
            field=models.PositiveIntegerField(default=44100),
        ),
    ]
