# Generated by Django 3.2.15 on 2022-10-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0087_auto_20221013_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_get_latest_surveys',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_register_user',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_set_fcm_token',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_set_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
