# Generated by Django 3.2.15 on 2022-10-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0089_auto_20221021_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_os_version',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_version_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_version_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
