# Generated by Django 3.2.15 on 2022-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0091_alter_devicesettings_check_for_new_surveys_frequency_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='accelerometer_frequency',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='gyro_frequency',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
