# Generated by Django 3.2.15 on 2022-11-03 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0091_alter_devicesettings_check_for_new_surveys_frequency_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='accelerometer_frequency',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='gyro_frequency',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='accelerometer_off_duration_seconds',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='accelerometer_on_duration_seconds',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='ambient_audio_bitrate',
            field=models.PositiveIntegerField(default=24000, validators=[django.core.validators.MinValueValidator(16000)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='ambient_audio_off_duration_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='ambient_audio_on_duration_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='ambient_audio_sampling_rate',
            field=models.PositiveIntegerField(default=44100, validators=[django.core.validators.MinValueValidator(16000)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='bluetooth_on_duration_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='bluetooth_total_duration_seconds',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='check_for_new_surveys_frequency_seconds',
            field=models.PositiveIntegerField(default=3600, validators=[django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='create_new_data_files_frequency_seconds',
            field=models.PositiveIntegerField(default=900, validators=[django.core.validators.MinValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='devicemotion_off_duration_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='devicemotion_on_duration_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='gps_off_duration_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='gps_on_duration_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='gyro_off_duration_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='gyro_on_duration_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='magnetometer_off_duration_seconds',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='magnetometer_on_duration_seconds',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='seconds_before_auto_logout',
            field=models.PositiveIntegerField(default=600, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='upload_data_files_frequency_seconds',
            field=models.PositiveIntegerField(default=3600, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='devicesettings',
            name='wifi_log_frequency_seconds',
            field=models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(10)]),
        ),
    ]
