# Generated by Django 3.2.16 on 2022-12-12 13:36

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0094_auto_20221205_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='password_force_reset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='researcher',
            name='password_last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='study',
            name='password_max_age_days',
            field=models.PositiveIntegerField(default=365, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='study',
            name='password_max_age_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='password_minimum_length',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
