# Generated by Django 3.2.16 on 2022-12-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0095_auto_20221212_1336'),
    ]
    # we don't want this default value to be applied to existing users so it is set to True in a
    # migration following the addition of the field
    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='password_force_reset',
            field=models.BooleanField(default=True),
        ),
    ]
