# Generated by Django 3.2.16 on 2022-12-20 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0096_alter_researcher_password_force_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='password_min_length',
            field=models.SmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(8)]),
        ),
        migrations.AlterField(
            model_name='study',
            name='password_minimum_length',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
