# Generated by Django 3.2.16 on 2022-12-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0097_auto_20221220_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_sessions', to='database.researcher')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
        ),
    ]
