# Generated by Django 3.2.16 on 2023-01-10 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0098_researchersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='mfa_token',
            field=models.CharField(blank=True, max_length=52, null=True, validators=[django.core.validators.RegexValidator('[2-7A-Z]+={0,6}'), django.core.validators.MinLengthValidator(52)]),
        ),
        migrations.AddField(
            model_name='study',
            name='mfa_required',
            field=models.BooleanField(default=False),
        ),
    ]
