# Generated by Django 3.2.16 on 2023-02-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0099_auto_20230110_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_get_latest_device_settings',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
