# Generated by Django 3.2.19 on 2023-06-23 18:04, modified

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import StateApps


def fill_username(apps: StateApps, schema_editor):
    Researcher = apps.get_model('database', 'Researcher')
    # populate username on DataAccessRecords using the researcher's username
    for researcher in Researcher.objects.all():
        researcher.data_access_record.update(username=researcher.username)
    
    # for some reason bulk updating DataAccessRecords using the researcher's username like this
    # doesn't work, fails with: Joined field references are not permitted in this query
    # Researcher.objects.all().update(username=F('data_access_record__username'))

class Migration(migrations.Migration):
    
    dependencies = [
        ('database', '0102_forestversion'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='dataaccessrecord',
            name='username',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.RunPython(fill_username, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='apikey',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='database.researcher'),
        ),
        migrations.AlterField(
            model_name='dataaccessrecord',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_record', to='database.researcher'),
        ),
        migrations.AlterField(
            model_name='dataaccessrecord',
            name='username',
            field=models.CharField(max_length=32, null=False),
        ),
    ]
