# Generated by Django 3.2.20 on 2023-08-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0103_auto_20230623_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='device_status_report',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
