# Generated by Django 3.2.20 on 2023-08-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0104_participant_device_status_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='unknown_timezone',
            field=models.BooleanField(default=True),
        ),
    ]
