# Generated by Django 3.2.20 on 2023-10-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0106_researcher_most_recent_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicesettings',
            name='consent_form_text',
            field=models.TextField(blank=True, default='I have read and understood the information about the study and all of my questions about the study have been answered by the study researchers.'),
        ),
    ]
