# Generated by Django 3.2.23 on 2023-12-06 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0108_auto_20231128_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='unregistered',
            new_name='permanently_retired',
        ),
        migrations.AlterField(
            model_name='participant',
            name='device_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='participant',
            name='os_type',
            field=models.CharField(blank=True, choices=[('IOS', 'IOS'), ('ANDROID', 'ANDROID'), ('', '')], max_length=16),
        ),
        migrations.AlterField(
            model_name='participant',
            name='patient_id',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('^[1-9a-z]+$', message='This field can only contain characters 1-9 and a-z.')]),
        ),
    ]
