# Generated by Django 3.2.23 on 2024-01-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0109_auto_20231206_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='enable_aggressive_background_persistence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='enable_beta_features',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='enable_binary_uploads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='enable_developer_datastream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='enable_heartbeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='enable_new_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
