# Generated by Django 3.2.23 on 2024-01-18 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0110_auto_20240110_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_heartbeat_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AppHeartbeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heartbeats', to='database.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
