# Generated by Django 3.2.23 on 2024-01-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0110_auto_20240110_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
