# Generated by Django 3.2.23 on 2024-02-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0112_participantactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appheartbeats',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
