# Generated by Django 3.2.24 on 2024-03-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0114_devicestatusreporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='enable_extensive_device_info_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
