# Generated by Django 4.2.11 on 2024-03-28 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0117_researcher_last_login_time_alter_survey_survey_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetoprocess',
            name='app_version',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='AppVersionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('app_version', models.CharField(max_length=16)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_version_history', to='database.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
