# Generated by Django 4.2.11 on 2024-04-08 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0119_remove_appversionhistory_app_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='heartbeat_message',
            field=models.TextField(default='Beiwe may not be running correctly, please open the Beiwe app.'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='heartbeat_timer_minutes',
            field=models.PositiveIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
