# Generated by Django 4.2.11 on 2024-04-09 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0119_remove_appversionhistory_app_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesettings',
            name='heartbeat_message',
            field=models.TextField(default='Beiwe may not be running correctly, please open the Beiwe app.'),
        ),
        migrations.AddField(
            model_name='devicesettings',
            name='heartbeat_timer_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_heartbeat_checkin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
