# Generated by Django 4.2.11 on 2024-05-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0121_alter_devicesettings_heartbeat_timer_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='enable_heartbeat',
        ),
    ]
