# Generated by Django 4.2.11 on 2024-05-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    
    dependencies = [
        ('database', '0123_universal_api_keys'),
    ]
    
    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='has_tableau_api_permissions',
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='researcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='database.researcher'),
        ),
    ]
