# Generated by Django 4.2.11 on 2024-06-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0126_devicestatusreporthistory_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='manually_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
