# Generated by Django 4.2.15 on 2024-09-13 20:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0128_manual_archived_event_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='checkin_time',
        ),
        migrations.AddField(
            model_name='archivedevent',
            name='confirmed_received',
            field=models.BooleanField(db_index=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='earliest_possible_time_of_push_notification_resend',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='SurveyNotificationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notification_uuid', models.UUIDField(default=uuid.uuid4)),
                ('applied', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_reports', to='database.participant')),
            ],
            options={
                'unique_together': {('participant', 'notification_uuid')},
            },
        ),
    ]
